name: Start project

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore
      run: dotnet restore ./CodewarsGitHubLogger/CodewarsGitHubLogger.csproj
    - name: Build
      run: dotnet build ./CodewarsGitHubLogger/CodewarsGitHubLogger.csproj --no-restore
    - name: Test
      run: dotnet test ./CodewarsGitHubLogger/CodewarsGitHubLogger.csproj --no-build --verbosity normal
    - name: Run
      run: dotnet run --project ./CodewarsGitHubLogger/CodewarsGitHubLogger.csproj
