name: Get katas

env:
  CODEWARS_USERNAME: ${{ secrets.CODEWARS_USERNAME }}
  GITHUB_USERNAME: ${{ secrets.USERNAME_GITHUB }}
  GITHUB_PASSWORD: ${{ secrets.PASSWORD_GITHUB }}

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 13 * * 1"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Test
      run: dotnet test ./CodewarsGitHubLogger/CodewarsGitHubLogger.csproj --verbosity normal
    - name: Run
      run: dotnet run --project ./CodewarsGitHubLogger/CodewarsGitHubLogger.csproj -- ${{ env.CODEWARS_USERNAME }} ${{ env.USERNAME_GITHUB }} ${{ env.PASSWORD_GITHUB }}
