name: Get data

on:
  push:
    branches: [ main ]
    paths: "CodewarsGitHubLogger/"
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Run C# file
      run: |
        dotnet run
